function plot_route(robot_state,prerotation,action)
% Using [RGB] to plot the corresponding colored grid world
rgb_1 = [1 1 1 1 1 1;...
         1 1 1 1 0 1;...
         1 1 1 1 1 1;...
         1 1 1 1 1 1;...
         1 1 1 1 1 1;...
         1 1 1 1 1 1];
rgb_2 = [0 0 0 0 0 0;...
         0 1 1 1 1 0;...
         0 1 1 1 1 0;...
         0 1 1 1 1 0;...
         0 1 1 1 1 0;...
         0 0 0 0 0 0];
rgb_3 = [0 0 0 0 0 0;...
         0 1 1 0 0 0;...
         0 1 1 0 1 0;...
         0 1 1 1 1 0;...
         0 1 1 1 1 0;...
         0 0 0 0 0 0];
rgb = cat(3,rgb_1,rgb_2,rgb_3);
[rows,cols,deps] = size(rgb);
GW = figure(1);
gridWorld = imshow(rgb,'InitialMagnification','fit');
set(gca,'ticklabelinterpreter','latex');
title('Robot Trajectory','fontsize',20,'interpreter','latex');

% Plot the robot state on grid world
% Number shown on the grid is the heading
for gw_x = 1:rows
    for gw_y = 1:cols
        if (robot_state(gw_x,gw_y) ~= 0)
            text(gw_y,gw_x,num2str(robot_state(gw_x,gw_y)),...
                'HorizontalAlignment','center','VerticalAlignment','middle');
            xlabelStr = ['For Next State: Action = ',num2str(action),' Prerotation = ',num2str(prerotation)];
            xlabel(xlabelStr,'fontsize',18,'interpreter','latex');
            drawnow;    refreshdata;
        end
    end
end

% 'tightfig.m' is an open sourse function
% Trim off the extra region in the figure
tightfig;
end 

